#!/bin/sh
####################################################################################################
#
# FILENAME:     setup-tools/validate-demo
#
# SUMMARY:      Validates a demo project, usually against a scratch org.
#
# DESCRIPTION:  ##ADD_DESCRIPTIION_HERE##
#
# INSTRUCTIONS: Execute the following command relative to your project's root directory:  
#               ./setup-tools/validate-demo
#
# RELATED DOCS: TODO: ?????
#               └─ https://???.???.com
#
#               TODO: ?????
#               ├─ https://www.????.com
#               └─ https://www.????.com
#
####################################################################################################
#
##
###
#### LOAD SHARED FUNCTIONS LIBRARY #################################################################
###
##
#
if [ ! -r `dirname $0`/lib/shared-functions.sh ]; then
  echo "\nFATAL ERROR: `tput sgr0``tput setaf 1`Could not load setup-tools/lib/shared-functions.sh.  File not found.\n"
  exit 1
fi
REQUESTED_INSTALLATION_OPTION="VALIDATE_DEMO"
source `dirname $0`/lib/shared-functions.sh
#
##
###
#### CONFIRM SCRIPT EXECUTION ######################################################################
###
##
#
confirmScriptExecution "Validate this Demo's deployment steps against a Scratch Org?"
#
##
###
#### CREATE LOCAL VARIABLES ########################################################################
###
##
#
# No local variables needed by the default version of this script.
# If you decide to customize this script, create your variables here.
#
##
###
#### FUNCTION: deleteScratchOrg () #################################################################
###
##
#
deleteScratchOrg () {
  # Delete the current scratch org.
  echoStepMsg "Delete the $TARGET_ORG_ALIAS scratch org"
  echo "Executing force:org:delete -p -u $TARGET_ORG_ALIAS -v $DEV_HUB_ALIAS" 
  (cd $PROJECT_ROOT && exec sfdx force:org:delete -p -u $SCRATCH_ORG_ALIAS -v $DEV_HUB_ALIAS )
}


#
##
###
#### EXECUTE DEMO VALIDATION LOGIC #################################################################
###
##
#
# For most demos, the only thing that's different between `validate-demo` and `deploy-demo` is the
# target org.  Demos are VALIDATED in scratch orgs and DEPLOYED to DE/EE/TRIAL orgs.  
#
# The standard behavior here is to leverage the logic present in `deploy-demo` by sourcing it and
# having it run with "VALIDATE_DEMO" set as the INSTALLATION_OPTION.
#
# NOTE: Unless you have good reason to create a distinct demo validation script, this file should
# be left as-is.  All of your demo setup logic should be put inside `src/deploy-demo`.

# First, delete the current demo validation scratch org (if it exists).


source `dirname $0`/deploy-demo-app



resetStepMsgCounter 6
#
##
###
#### INSTALL PARTNER PACKAGES ######################################################################
###
##
#
# Install the MAIN Partner Package.
installPackage $DEMO_PACKAGE_VERSION_ID_01 \
               "MAIN Partner Package" \
               "Install the Main Partner Package into the $TARGET_DEMO_ORG_ALIAS org"

# Install the SECOND Partner Package. (uncomment if needed)
#installPackage $DEMO_PACKAGE_VERSION_ID_02 \
#               "SECOND Partner Package" \
#               "Install the Second Partner Package into the $TARGET_DEMO_ORG_ALIAS org"

# Install the THIRD Partner Package. (uncomment if needed)
#installPackage $DEMO_PACKAGE_VERSION_ID_03 \
#               "THIRD Partner Package" \
#               "Install the Third Partner Package into the $TARGET_DEMO_ORG_ALIAS org"

# Install the FOURTH Partner Package. (uncomment if needed)
#installPackage $DEMO_PACKAGE_VERSION_ID_04 \
#               "FOURTH Partner Package" \
#               "Install the Fourth Partner Package into the $TARGET_DEMO_ORG_ALIAS org"

# Install the FIFTH Partner Package. (uncomment if needed)
#installPackage $DEMO_PACKAGE_VERSION_ID_05 \
#               "FIFTH Partner Package" \
#               "Install the Fifth Partner Package into the $TARGET_DEMO_ORG_ALIAS org"
#
##
###
#### POST-INSTALL MDAPI DEPLOYMENTS ################################################################
###
##
#

# Deploy Org Config Metadata
deployMdapiSource "org-config"

# Deploy App Config Metadata
deployMdapiSource "app-config"

# Deploy Data Config Metadata
deployMdapiSource "data-config"

#
##
###
#### ASSIGN PERMISSION SETS ########################################################################
###
##
#
# Assign packaged permission sets to specific users (ADMIN, PRIMARY, and/or SECONDARY).
assignPermset "FinServ__Advisor" \
              "$DEMO_ADMIN_USER,
               $DEMO_PRIMARY_USER,
               $DEMO_SECONDARY_USER"

# Repeat permission set assignments as many times as necessary using the following template:
#assignPermset "NameSpace__PermSetApiName" \
#              "$DEMO_ADMIN_USER,
#               $DEMO_PRIMARY_USER,
#               $DEMO_SECONDARY_USER"


#
##
###
#### IMPORT/CREATE DEMO DATA #######################################################################
###
##
#

echoStepMsg "Import/create demo-specifc data in the $TARGET_DEMO_ORG_ALIAS org"

#
##
###
#### ECHO CLOSING MESSAGE ##########################################################################
###
##
#
echoScriptCompleteMsg \
"Demo App has been successfully installed and configured."
exit 0

##END##