#!/bin/sh
####################################################################################################
#
# FILENAME:     setup-tools/validate-demo
#
# SUMMARY:      Validates a demo project, usually against a scratch org.
#
# DESCRIPTION:  ##ADD_DESCRIPTIION_HERE##
#
# INSTRUCTIONS: Execute the following command relative to your project's root directory:  
#               ./setup-tools/validate-demo
#
# RELATED DOCS: TODO: ?????
#               └─ https://???.???.com
#
#               TODO: ?????
#               ├─ https://www.????.com
#               └─ https://www.????.com
#
####################################################################################################
#
##
###
#### LOAD SHARED FUNCTIONS LIBRARY #################################################################
###
##
#
if [ ! -r `dirname $0`/lib/shared-functions.sh ]; then
  echo "\nFATAL ERROR: `tput sgr0``tput setaf 1`Could not load setup-tools/lib/shared-functions.sh.  File not found.\n"
  exit 1
fi
REQUESTED_INSTALLATION_OPTION="VALIDATE_DEMO"
source `dirname $0`/lib/shared-functions.sh
#
##
###
#### CONFIRM SCRIPT EXECUTION ######################################################################
###
##
#
confirmScriptExecution "Validate this Demo's deployment steps against a Scratch Org?"
#
##
###
#### CREATE LOCAL VARIABLES ########################################################################
###
##
#
# No local variables needed by the default version of this script.
# If you decide to customize this script, create your variables here.
#
##
###
#### FUNCTION: deleteScratchOrg () #################################################################
###
##
#
deleteScratchOrg () {
  # Delete the current scratch org.
  echoStepMsg "Delete the $DEMO_VALIDATION_ORG_ALIAS scratch org"
  echo "Executing force:org:delete -p -u $DEMO_VALIDATION_ORG_ALIAS -v $DEV_HUB_ALIAS" 
  (cd $PROJECT_ROOT && exec sfdx force:org:delete -p -u $DEMO_VALIDATION_ORG_ALIAS -v $DEV_HUB_ALIAS )
}
#
##
###
#### EXECUTE DEMO VALIDATION LOGIC #################################################################
###
##
#
# Start by deleting the old scratch org
deleteScratchOrg

# For most demos, the only thing that's different between `validate-demo` and `deploy-demo` is the
# target org.  Demos are VALIDATED in scratch orgs and DEPLOYED to DE/EE/TRIAL orgs.  
#
# The standard behavior here is to leverage the logic present in `deploy-demo` by sourcing it and
# having it run with "VALIDATE_DEMO" set as the INSTALLATION_OPTION.
#
# NOTE: Unless you have good reason to create a distinct demo validation script, this file should
# be left as-is.  All of your demo setup logic should be put inside `src/deploy-demo`.
source `dirname $0`/deploy-demo
#
##
###
#### POST-DEPLOY OPERATIONS ########################################################################
###
##
#
# If you want to add any special "validation only" operations AFTER the logic in `deploy-demo` runs
# you can add it here.
#
##
###
#### ECHO CLOSING MESSAGE ##########################################################################
###
##
#
echoScriptCompleteMsg \
"Demo App has been validated successfully"
exit 0

##END##